// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jywgxqgfeqdmwrmareiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5d2d4cWdmZXFkbXdybWFyZWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDk0MjksImV4cCI6MjA2NDg4NTQyOX0.zYQnZzMeMbPX5H6cL_UL0QgHYlW7SyjETE3MB9RxgdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);